import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import Script from "next/script";

const DynamicMap = dynamic(() => import("../components/Map/Map"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      {/* <Script
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_MAPS_API_KEY}&libraries=places`}
        strategy="beforeInteractive"
      /> */}
      <body className="relative h-full overflow-hidden">
        <div className="relative h-full">
          <div className="absolute inset-0 z-10">
            <DynamicMap />
          </div>
          <div
            className={`absolute inset-0 z-20 pointer-events-none ${inter.className}`}
          >
            <div className="pointer-events-auto">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
